USE [CESI-EATS]
GO

/****** Object:  Table [dbo].[Market_Logs]    Script Date: 12/06/2022 20:30:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Market_Logs](
	[LogID] [uniqueidentifier] NOT NULL,
	[MarketID] [uniqueidentifier] NULL,
	[LogInTime] [datetime] NULL,
	[LogOutTime] [datetime] NULL,
 CONSTRAINT [PK_Market_Logs] PRIMARY KEY CLUSTERED 
(
	[LogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Market_Logs]  WITH CHECK ADD  CONSTRAINT [FK_Market_Logs] FOREIGN KEY([MarketID])
REFERENCES [dbo].[Market] ([MarketID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Market_Logs] CHECK CONSTRAINT [FK_Market_Logs]
GO

